server:
  port: 8084
  host: "0.0.0.0"
  environment: "development"
  debug: true
  read_timeout: "30s"
  write_timeout: "30s"

database:
  host: "localhost"
  port: 5432
  user: "auth_user"
  password: "auth_pass"
  database: "combat_db"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: "30m"

jwt:
  secret: "your-super-secret-jwt-key-change-in-production-minimum-64-characters"

combat:
  max_combat_duration: "30m"
  turn_timeout: "30s"
  action_timeout: "10s"
  max_participants: 20
  max_simultaneous_combats: 1000
  base_damage_multiplier: 1.0
  critical_damage_bonus: 0.5
  level_difference_bonus: 0.1
  pvp_enabled: true
  pvp_level_difference: 10
  pvp_cooldown: "5m"
  max_actions_per_second: 3
  validate_positions: true
  anti_cheat_enabled: true

services:
  auth:
    url: "http://auth-service:8081"
    timeout: "5s"
    retries: 3
  player:
    url: "http://player-service:8082"
    timeout: "5s"
    retries: 3
  world:
    url: "http://world-service:8083"
    timeout: "3s"
    retries: 2

rate_limit:
  combat_actions_per_minute: 180
  spell_casts_per_minute: 120
  burst_size: 10
  cleanup_interval: "5m"

monitoring:
  prometheus_port: 9094
  metrics_path: "/metrics"
  health_path: "/health"

nats:
  url: "nats://nats:4222"
  cluster_id: "mmorpg-cluster"
  client_id: "combat-service"
  connect_timeout: "10s"
  reconnect_delay: "2s"
  max_reconnect_attempts: 10

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  check_origin: false
  ping_period: "54s"
  pong_wait: "60s"
  write_wait: "10s"
