name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: auth_user
          POSTGRES_PASSWORD: auth_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - name: Lint services
        run: |
          for service in services/*/; do
            if [ -f "$service/go.mod" ]; then
              echo "Linting $service"
              cd "$service"
              golangci-lint run --timeout=5m || exit 1
              cd ../..
            fi
          done
      - name: Build all services
        run: |
          make build
      - name: Run unit tests
        run: |
          make test
      - name: Build Docker images
        run: |
          docker-compose build 